[book]
authors = ["jon roethke"]
language = "en"
multilingual = false
src = "src"
title = "arch-book"

[output.html]
git-repository-url = "https://github.com/arch-network/arch-book"
edit-url-template = "https://github.com/arch-network/arch-book/edit/main/{path}"

[rust]
edition = "2021"
